from __future__ import annotations

from io import BytesIO

def _section_table(rows, headers, colors, Table, TableStyle):
    data = [headers] + rows
    table = Table(data, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def generate_ca_export_pdf(fy: str, user: str, deductions_df, summary: dict, regime_result: dict) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except Exception as e:
        raise RuntimeError("reportlab is required for CA PDF export. Install dependencies first.") from e

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"WealthOS Tax Summary FY {fy} | {user}", styles["Title"]))
    story.append(Spacer(1, 12))

    # 1) Section 80C schedule
    s80c_types = {"epf", "ppf", "elss", "nsc", "tax_saver_fd", "life_insurance_premium", "home_loan_principal", "other_80c"}
    s80c_rows = []
    for _, row in deductions_df.iterrows():
        if row.get("Instrument Type") in s80c_types:
            s80c_rows.append([str(row.get("Instrument Type", "")), f"{float(row.get('Amount Invested', 0.0)):,.2f}"])
    story.append(Paragraph("1. Section 80C Schedule", styles["Heading3"]))
    story.append(_section_table(s80c_rows or [["-", "0.00"]], ["Instrument", "Amount (Rs)"], colors, Table, TableStyle))
    story.append(Spacer(1, 12))

    # 2) Section 80CCD(1B)
    story.append(Paragraph("2. Section 80CCD(1B) NPS", styles["Heading3"]))
    story.append(Paragraph(f"NPS Invested: Rs {summary['s_nps']['invested']:,.2f}", styles["BodyText"]))
    story.append(Spacer(1, 12))

    # 3) Section 80D
    story.append(Paragraph("3. Section 80D Health Insurance", styles["Heading3"]))
    s80d_rows = [
        ["Self", f"{summary['s80d']['self']:,.2f}"],
        ["Parents", f"{summary['s80d']['parents']:,.2f}"],
        ["Total", f"{summary['s80d']['total']:,.2f}"],
    ]
    story.append(_section_table(s80d_rows, ["Category", "Amount (Rs)"], colors, Table, TableStyle))
    story.append(Spacer(1, 12))

    # 4) Regime Recommendation
    story.append(Paragraph("4. Regime Recommendation", styles["Heading3"]))
    rec = regime_result.get("recommended", "new")
    saving = float(regime_result.get("saving", 0.0))
    story.append(Paragraph(f"Recommended Regime: {rec.upper()}", styles["BodyText"]))
    story.append(Paragraph(f"Potential Saving: Rs {saving:,.2f}", styles["BodyText"]))
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by WealthOS - verify with your CA before filing",
            styles["Italic"],
        )
    )

    doc.build(story)
    return buffer.getvalue()
